<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="54513" started-at="2019-04-29T06:50:06Z" finished-at="2019-04-29T06:51:00Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="54513" started-at="2019-04-29T06:50:06Z" finished-at="2019-04-29T06:51:00Z">
      <class name="com.Test.PageTest.HomepageTest">
        <test-method status="PASS" signature="Start()[pri:0, instance:com.Test.PageTest.HomepageTest@649d209a]" name="Start" is-config="true" duration-ms="17205" started-at="2019-04-29T12:20:06Z" finished-at="2019-04-29T12:20:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Start -->
        <test-method status="FAIL" signature="Url()[pri:1, instance:com.Test.PageTest.HomepageTest@649d209a]" name="Url" duration-ms="34" started-at="2019-04-29T12:20:23Z" finished-at="2019-04-29T12:20:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://pcsv2dev.azurewebsites.net] but found [http://pcsv2dev.azurewebsites.net/#/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://pcsv2dev.azurewebsites.net] but found [http://pcsv2dev.azurewebsites.net/#/]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.Test.PageTest.HomepageTest.Url(HomepageTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Url -->
        <test-method status="PASS" signature="Close()[pri:0, instance:com.Test.PageTest.HomepageTest@649d209a]" name="Close" is-config="true" duration-ms="1274" started-at="2019-04-29T12:20:23Z" finished-at="2019-04-29T12:20:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
        <test-method status="PASS" signature="Start()[pri:0, instance:com.Test.PageTest.HomepageTest@649d209a]" name="Start" is-config="true" duration-ms="16264" started-at="2019-04-29T12:20:24Z" finished-at="2019-04-29T12:20:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Start -->
        <test-method status="PASS" signature="login()[pri:2, instance:com.Test.PageTest.HomepageTest@649d209a]" name="login" duration-ms="437" started-at="2019-04-29T12:20:40Z" finished-at="2019-04-29T12:20:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="Close()[pri:0, instance:com.Test.PageTest.HomepageTest@649d209a]" name="Close" is-config="true" duration-ms="1532" started-at="2019-04-29T12:20:41Z" finished-at="2019-04-29T12:20:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
        <test-method status="PASS" signature="Start()[pri:0, instance:com.Test.PageTest.HomepageTest@649d209a]" name="Start" is-config="true" duration-ms="16299" started-at="2019-04-29T12:20:42Z" finished-at="2019-04-29T12:20:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Start -->
        <test-method status="PASS" signature="Title()[pri:3, instance:com.Test.PageTest.HomepageTest@649d209a]" name="Title" duration-ms="11" started-at="2019-04-29T12:20:59Z" finished-at="2019-04-29T12:20:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Title -->
        <test-method status="PASS" signature="Close()[pri:0, instance:com.Test.PageTest.HomepageTest@649d209a]" name="Close" is-config="true" duration-ms="1457" started-at="2019-04-29T12:20:59Z" finished-at="2019-04-29T12:21:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Close -->
      </class> <!-- com.Test.PageTest.HomepageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
